all:

clean:
	rm -f src/*.py[oc]
	rm -f src/ui/fremantle/*.py[oc]
	rm -rf src/ui/*.py[oc]
	rm -f src/ui/diablo/*.py[oc]
	rm -f src/ui/desktop/*.py[oc]
	rm -f src/eveapi/*.py[oc]
	find . -name *~ -exec rm -f {} \;
